auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: BeiYuu.com
url: http://alberta0714.github.io
feed: /atom.xml
author_info: <a href="http://alberta0714.github.io">Albert.Sun.</a>